# Generated by Django 4.2.2 on 2023-06-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created',
        ),
        migrations.RemoveField(
            model_name='author',
            name='done',
        ),
    ]
