# Generated by Django 4.2.2 on 2023-06-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fullname_author_name_remove_author_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='born_location',
        ),
    ]
